---
- id: python-pypi-version-check
  name: python-pypi-version-check
  description: Check if Python package already exists on PYPI.
  # entry: hooks/pypi_bumpversion_check-check
  entry: python-pypi-version-check
  language: python

- id: find-and-replace-strings
  name: find-and-replace-strings
  description: Check if Python package already exists on PYPI.
  entry: find-and-replace-strings
  # entry: hooks/find_and_replace_strings
  language: python
