---
name: precommit

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, feat/IDP-43-modular]

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.1
