---
name: Tests

on:
  push:
    branches: [main, develop, IDP-43-modular]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run tests
        run: |
          pytest cpk_lib_python_github/github_app_token_generator_package/tests/ -v

      - name: Run tests with coverage
        run: |
          pytest cpk_lib_python_github/github_app_token_generator_package/tests/ \
            --cov=cpk_lib_python_github.github_app_token_generator_package.github_app_token_generator \
            --cov-report=term-missing

  test-installation:
    name: Test Package Installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Test CLI command
        run: |
          github-app-token-generator --help
